title: "Toward applications of the BxC toolkit"
authors: "Maci, D., Keppens, R., Bacchini, F."
year: 2025
journal: "Journal of Physics: Conference Series"
status: published
doi: "10.1088/1742-6596/2997/1/012003"
fabio_position: contributing
